/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sell;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JPanel;
import model.dao.InvocesPrintDAO;
import model.dao.InvoicesDAO;
import model.dto.Invoices;
import model.dto.InvoicesPrint;
import model.dto.Product;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import view.MainFrm;

/**
 *
 * @author vtson
 */
public class InvoiceDgl extends javax.swing.JDialog {

    Product p;

    /**
     * Creates new form InvoiceDgl
     */
    public InvoiceDgl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public InvoiceDgl(java.awt.Frame parent, boolean modal, Product p) {
        super(parent, modal);
        initComponents();
        this.p = p;
        lblTenSP.setText(lblTenSP.getText() + p.getName());
        lblNguoiBan.setText(lblNguoiBan.getText() + MainFrm.account.getUsername());
        lblNgayBan.setText(lblNgayBan.getText() + Calendar.getInstance().getTime().toString());
        lblSoLuong.setText(lblSoLuong.getText() + p.getQuantity());
        lblDongia.setText(lblDongia.getText() + p.getPrice());
        lblTongtien.setText(lblTongtien.getText() + (p.getPrice() * p.getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenSP = new javax.swing.JLabel();
        lblNguoiBan = new javax.swing.JLabel();
        lblNgayBan = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblDongia = new javax.swing.JLabel();
        lblTongtien = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        txtInvoice = new javax.swing.JTextField();

        setTitle("Invoice");

        lblTenSP.setText("Tên sản phẩm: ");

        lblNguoiBan.setText("Người bán:");

        lblNgayBan.setText("Ngày bán:");

        lblSoLuong.setText("Số lượng:");

        lblDongia.setText("Đơn giá:");

        lblTongtien.setText("Tổng tiền:");

        btnOK.setText("Ok");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        txtInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInvoice)
                    .addComponent(lblTongtien)
                    .addComponent(lblDongia)
                    .addComponent(lblSoLuong)
                    .addComponent(lblNgayBan)
                    .addComponent(lblNguoiBan)
                    .addComponent(lblTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTenSP)
                .addGap(18, 18, 18)
                .addComponent(lblNguoiBan)
                .addGap(18, 18, 18)
                .addComponent(lblNgayBan)
                .addGap(18, 18, 18)
                .addComponent(lblSoLuong)
                .addGap(18, 18, 18)
                .addComponent(lblDongia)
                .addGap(18, 18, 18)
                .addComponent(lblTongtien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        //Nút này sẽ thực hiện tạo ra hóa đơn cho người mua
        //Đồng thời sẽ lưu vào dữ liệu hóa đơn, chi tiết hóa đơn
        //sau đó in ra thống báo là thành công hay thất bại cho người dùng
        InvoicesDAO iDao = new InvoicesDAO();
        Invoices in = new Invoices();
        in.setAccountid(MainFrm.account.getAccountId());
        in.setProductid(this.p.getProductid());
        in.setDatesell(Calendar.getInstance().getTime());
        in.setInvoiceid(Integer.parseInt(txtInvoice.getText().trim()));
        iDao.create(in);
        this.dispose();
        JFrame f = new JFrame("Hóa đơn thanh toán");
        ArrayList<InvoicesPrint> l =  (ArrayList<InvoicesPrint>) new InvocesPrintDAO().readByUserid(MainFrm.account.getAccountId());
        f.getContentPane().add(getEnumerationViewer(l, true));
    }//GEN-LAST:event_btnOKActionPerformed
    @SuppressWarnings(value = "unchecked")
    public JPanel getEnumerationViewer(ArrayList<InvoicesPrint> arr, boolean isEnumeration) {
        JPanel viewer = null;
        String reportSource = System.getProperty("user.dir") + "\\InvoicesReport.jrxml";
//String reportSource = new File("ThongkePublisher.jrxml").getAbsolutePath();
//String reportDest = System.getProperty("user.dir") + "\\FeeAccountReport.html";
        try {
            HashMap parameterMap = new HashMap();
            parameterMap.put("username", MainFrm.account.getUsername());
            
            ArrayList reportRows = new ArrayList();
            float sum = 0;
            for (int i = 0; i < arr.size(); i++) {
                HashMap rowMap = new HashMap();
                rowMap.put("datesell", arr.get(i).getDatesell().toString());
                rowMap.put("namep", arr.get(i).getNamep());
                rowMap.put("price", arr.get(i).getPrice());
                rowMap.put("quantity", arr.get(i).getQuantity());
                sum += arr.get(i).getPrice()*arr.get(i).getQuantity();
                reportRows.add(rowMap);
            }
            parameterMap.put("total", sum);
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,
                    parameterMap, new JRMapCollectionDataSource(reportRows));
//JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);

            JasperViewer.viewReport(jasperPrint);

            String path = System.getProperty("user.dir") + "\\";
//JasperExportManager.exportReportToPdfFile(jasperPrint, path + "customer.pdf");
            viewer = new JRViewer(jasperPrint);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return viewer;
    }
    private void txtInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceDgl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvoiceDgl dialog = new InvoiceDgl(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblDongia;
    private javax.swing.JLabel lblNgayBan;
    private javax.swing.JLabel lblNguoiBan;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTongtien;
    private javax.swing.JTextField txtInvoice;
    // End of variables declaration//GEN-END:variables
}
