/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sell;

import view.*;
import controller.ProductAction;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.dto.Product;

/**
 *
 * @author USER
 */
public class SellProductIFrm extends javax.swing.JInternalFrame {

    ProductAction actions;

    /**
     * Creates new form ProductIFrm
     */
    public SellProductIFrm() {
        initComponents();
        actions = new ProductAction();
        loadTable(actions.readAll(), this.tblProduct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnSell = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSellProduct = new javax.swing.JTable();
        btnPay = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProduct);

        btnSell.setText("Sell");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        tblSellProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSellProduct);

        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSell, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPay, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPay)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Product> lSP = new ArrayList<Product>();
    Product p = new Product();
    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        int rowselected = tblProduct.getSelectedRow();
        p.setProductid((int) tblProduct.getValueAt(rowselected, 0));
        p.setName((String) tblProduct.getValueAt(rowselected, 1));
        p.setProducerid((int) tblProduct.getValueAt(rowselected, 2));
        p.setPrice((float) tblProduct.getValueAt(rowselected, 3));
        p.setQuantity(1);
        lSP.add(p);
        loadTable(lSP, tblSellProduct);
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        int dsProduct = tblSellProduct.getRowCount();
        p.setQuantity(Integer.parseInt(tblSellProduct.getValueAt(0, 4).toString().trim()));
        InvoiceDgl in = new InvoiceDgl(LoginDgl.mainfrm, true, p);
        in.setVisible(true);
    }//GEN-LAST:event_btnPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSell;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblSellProduct;
    // End of variables declaration//GEN-END:variables

    private void loadTable(List<Product> readAll, JTable tblProduct) {
        Vector col = new Vector();
        col.add("ProductID");
        col.add("Name");
        col.add("ProducerID");
        col.add("Price");
        col.add("Quantity");
        Vector rows = new Vector();
        for (Product p : readAll) {
            Vector row = new Vector();
            row.add(p.getProductid());
            row.add(p.getName());
            row.add(p.getProducerid());
            row.add(p.getPrice());
            row.add(p.getQuantity());
            rows.add(row);
        }
        tblProduct.setModel(new DefaultTableModel(rows, col));
        tblProduct.updateUI();
        jScrollPane1.setViewportView(this.tblProduct);
    }
}
