/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RoleFunctionAction;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dto.RoleFunction;

/**
 *
 * @author BVMT
 */
public class RoleFuntionFrm extends javax.swing.JFrame {

    RoleFunctionAction actionss;

    /**
     * Creates new form RoleFuntionFrm
     */
    public RoleFuntionFrm() {
        initComponents();
        setLocationRelativeTo(null);
        actionss = new RoleFunctionAction();
        loadTable(actionss.readAll());

    }

    private void loadTable(List<RoleFunction> list) {
        Vector col = new Vector();
        col.add("ID");
        col.add("RoleID");
        col.add("FuntionID");
        Vector rows = new Vector();
        for (RoleFunction rofu : list) {
            Vector row = new Vector();
            row.add(rofu.getiD());
            row.add(rofu.getRoleID());
            row.add(rofu.getFuntionID());
            rows.add(row);
        }
        tblRoleFuntion.setModel(new DefaultTableModel(rows, col));
        tblRoleFuntion.updateUI();
        jScrollPane1.setViewportView(this.tblRoleFuntion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoleFuntion = new javax.swing.JTable();
        lblID = new javax.swing.JLabel();
        lblRoleID = new javax.swing.JLabel();
        lblFuntionID = new javax.swing.JLabel();
        tbnLamtuoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtRoleID = new javax.swing.JTextField();
        txtFuntionID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRoleFuntion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRoleFuntion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoleFuntionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRoleFuntion);

        lblID.setText("ID");

        lblRoleID.setText("RoleID");

        lblFuntionID.setText("FunctionID");

        tbnLamtuoi.setText("Làm tươi");
        tbnLamtuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnLamtuoiActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtRoleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoleIDActionPerformed(evt);
            }
        });

        txtFuntionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuntionIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbnLamtuoi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFuntionID)
                        .addComponent(lblRoleID)
                        .addComponent(lblID)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapnhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID)
                            .addComponent(txtRoleID)
                            .addComponent(txtFuntionID, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoleID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuntionID)
                    .addComponent(txtFuntionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbnLamtuoi)
                    .addComponent(btnThem)
                    .addComponent(btnCapnhat)
                    .addComponent(btnXoa))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoleIDActionPerformed

    private void txtFuntionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuntionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuntionIDActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        RoleFunction rolef = new RoleFunction();
        rolef.setiD(Integer.parseInt(txtID.getText()));
        rolef.setRoleID(Integer.parseInt(txtRoleID.getText()));
        rolef.setFuntionID(Integer.parseInt(txtFuntionID.getText()));
        if (actionss.create(rolef) == null) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadTable(actionss.readAll());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int indexSelected = tblRoleFuntion.getSelectedRow();
        if (indexSelected == -1) {
            JOptionPane.showMessageDialog(this, "Xoá thất bại");
        } else {
            if (actionss.delete(Integer.parseInt(txtID.getText()))) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadTable(actionss.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbnLamtuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnLamtuoiActionPerformed
        // TODO add your handling code here:
        txtFuntionID.setText("");
        txtID.setText("");
        txtRoleID.setText("");
    }//GEN-LAST:event_tbnLamtuoiActionPerformed

    private void tblRoleFuntionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoleFuntionMouseClicked
        // TODO add your handling code here:
        int indexSelected = tblRoleFuntion.getSelectedRow();
        txtID.setText(tblRoleFuntion.getValueAt(indexSelected, 0).toString());
        txtRoleID.setText(tblRoleFuntion.getValueAt(indexSelected, 1).toString());
        txtFuntionID.setText(tblRoleFuntion.getValueAt(indexSelected, 2).toString());
    }//GEN-LAST:event_tblRoleFuntionMouseClicked

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:
        RoleFunction role = new RoleFunction();
        role.setiD(Integer.parseInt(txtID.getText()));
        role.setRoleID(Integer.parseInt(txtRoleID.getText()));
        role.setFuntionID(Integer.parseInt(txtFuntionID.getText()));
        if (actionss.update(role)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            loadTable(actionss.readAll());
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
        }
    }//GEN-LAST:event_btnCapnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoleFuntionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoleFuntionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoleFuntionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoleFuntionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoleFuntionFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFuntionID;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblRoleID;
    private javax.swing.JTable tblRoleFuntion;
    private javax.swing.JButton tbnLamtuoi;
    private javax.swing.JTextField txtFuntionID;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtRoleID;
    // End of variables declaration//GEN-END:variables
}
